# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'band_interface/ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        self.Btn_Toggle.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px solid;")
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.verticalLayout_2.addWidget(self.Btn_Toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_1.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_4.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_4.addWidget(self.btn_page_2)
        self.btn_page_3 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_3.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_3.setObjectName("btn_page_3")
        self.verticalLayout_4.addWidget(self.btn_page_3)
        self.btn_page_4 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_4.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_4.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_4.setObjectName("btn_page_4")
        self.verticalLayout_4.addWidget(self.btn_page_4)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.firmware_btn = QtWidgets.QPushButton(self.page_1)
        self.firmware_btn.setStyleSheet("color: white;")
        self.firmware_btn.setObjectName("firmware_btn")
        self.horizontalLayout_3.addWidget(self.firmware_btn)
        self.led_btn = QtWidgets.QPushButton(self.page_1)
        self.led_btn.setStyleSheet("color: white;")
        self.led_btn.setObjectName("led_btn")
        self.horizontalLayout_3.addWidget(self.led_btn)
        self.raw_emg_button = QtWidgets.QPushButton(self.page_1)
        self.raw_emg_button.setStyleSheet("color: white;")
        self.raw_emg_button.setObjectName("raw_emg_button")
        self.horizontalLayout_3.addWidget(self.raw_emg_button)
        self.gesture_btn = QtWidgets.QPushButton(self.page_1)
        self.gesture_btn.setStyleSheet("color: white;")
        self.gesture_btn.setObjectName("gesture_btn")
        self.horizontalLayout_3.addWidget(self.gesture_btn)
        self.quaternion_btn = QtWidgets.QPushButton(self.page_1)
        self.quaternion_btn.setStyleSheet("color: white;")
        self.quaternion_btn.setObjectName("quaternion_btn")
        self.horizontalLayout_3.addWidget(self.quaternion_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.emg_btn = QtWidgets.QPushButton(self.page_1)
        self.emg_btn.setStyleSheet("color: white;")
        self.emg_btn.setObjectName("emg_btn")
        self.horizontalLayout_4.addWidget(self.emg_btn)
        self.motor_btn = QtWidgets.QPushButton(self.page_1)
        self.motor_btn.setStyleSheet("color: white;")
        self.motor_btn.setObjectName("motor_btn")
        self.horizontalLayout_4.addWidget(self.motor_btn)
        self.stop_emg_button = QtWidgets.QPushButton(self.page_1)
        self.stop_emg_button.setStyleSheet("color: white;")
        self.stop_emg_button.setObjectName("stop_emg_button")
        self.horizontalLayout_4.addWidget(self.stop_emg_button)
        self.stop_gesture_btn = QtWidgets.QPushButton(self.page_1)
        self.stop_gesture_btn.setStyleSheet("color: white;")
        self.stop_gesture_btn.setStyleSheet("color: white;")
        self.stop_gesture_btn.setObjectName("stop_gesture_btn")
        self.horizontalLayout_4.addWidget(self.stop_gesture_btn)
        self.stop_quat_btn = QtWidgets.QPushButton(self.page_1)
        self.stop_quat_btn.setStyleSheet("color: white;")
        self.stop_quat_btn.setObjectName("stop_quat_btn")
        self.horizontalLayout_4.addWidget(self.stop_quat_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.scan_btn = QtWidgets.QPushButton(self.page_1)
        self.scan_btn.setStyleSheet("color: white;")
        self.scan_btn.setObjectName("scan_btn")
        self.verticalLayout_7.addWidget(self.scan_btn)
        self.connect_btn = QtWidgets.QPushButton(self.page_1)
        self.connect_btn.setStyleSheet("color: white;")
        self.connect_btn.setObjectName("connect_btn")
        self.verticalLayout_7.addWidget(self.connect_btn)
        self.config_list = QtWidgets.QListWidget(self.page_1)
        self.config_list.setObjectName("config_list")
        self.verticalLayout_7.addWidget(self.config_list)
        self.data_read = QtWidgets.QListWidget(self.page_1)
        self.data_read.setObjectName("data_read")
        self.verticalLayout_7.addWidget(self.data_read)
        self.verticalLayout_7.setStretch(4, 20)
        self.verticalLayout_7.setStretch(5, 100)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #FFF;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.lbl_local_files = QtWidgets.QLabel(self.page_2)
        self.lbl_local_files.setStyleSheet("color: white;")
        self.lbl_local_files.setObjectName("lbl_local_files")
        self.hboxlayout.addWidget(self.lbl_local_files)
        self.lbl_external_files = QtWidgets.QLabel(self.page_2)
        self.lbl_external_files.setStyleSheet("color: white;")
        self.lbl_external_files.setObjectName("lbl_external_files")
        self.hboxlayout.addWidget(self.lbl_external_files)
        self.verticalLayout_6.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.list_local_files = QtWidgets.QListWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_local_files.sizePolicy().hasHeightForWidth())
        self.list_local_files.setSizePolicy(sizePolicy)
        self.list_local_files.setObjectName("list_local_files")
        self.hboxlayout1.addWidget(self.list_local_files)
        self.list_external_files = QtWidgets.QListWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_external_files.sizePolicy().hasHeightForWidth())
        self.list_external_files.setSizePolicy(sizePolicy)
        self.list_external_files.setObjectName("list_external_files")
        self.hboxlayout1.addWidget(self.list_external_files)
        self.verticalLayout_6.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.btn_upload = QtWidgets.QPushButton(self.page_2)
        self.btn_upload.setStyleSheet("color: white;")
        self.btn_upload.setObjectName("btn_upload")
        self.hboxlayout2.addWidget(self.btn_upload)
        self.btn_download = QtWidgets.QPushButton(self.page_2)
        self.btn_download.setStyleSheet("color: white;")
        self.btn_download.setObjectName("btn_download")
        self.hboxlayout2.addWidget(self.btn_download)
        self.verticalLayout_6.addLayout(self.hboxlayout2)
        self.lineEdit_filters = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_filters.setObjectName("lineEdit_filters")
        self.verticalLayout_6.addWidget(self.lineEdit_filters)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #FFF;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.frame_classification_buttons = QtWidgets.QFrame(self.page_3)
        self.frame_classification_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_classification_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_classification_buttons.setObjectName("frame_classification_buttons")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_classification_buttons)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btn_rf = QtWidgets.QPushButton(self.frame_classification_buttons)
        self.btn_rf.setStyleSheet("QPushButton {\n"
"                                    color: #FFF;\n"
"                                    background-color: #232323;\n"
"                                    border: 1px solid #555;\n"
"                                }\n"
"                                QPushButton:hover {\n"
"                                    background-color: #55AADD;\n"
"                                }")
        self.btn_rf.setObjectName("btn_rf")
        self.verticalLayout_9.addWidget(self.btn_rf)
        self.btn_lr = QtWidgets.QPushButton(self.frame_classification_buttons)
        self.btn_lr.setStyleSheet("QPushButton {\n"
"                                    color: #FFF;\n"
"                                    background-color: #232323;\n"
"                                    border: 1px solid #555;\n"
"                                }\n"
"                                QPushButton:hover {\n"
"                                    background-color: #55AADD;\n"
"                                }")
        self.btn_lr.setObjectName("btn_lr")
        self.verticalLayout_9.addWidget(self.btn_lr)
        self.btn_svm = QtWidgets.QPushButton(self.frame_classification_buttons)
        self.btn_svm.setStyleSheet("QPushButton {\n"
"                                    color: #FFF;\n"
"                                    background-color: #232323;\n"
"                                    border: 1px solid #555;\n"
"                                }\n"
"                                QPushButton:hover {\n"
"                                    background-color: #55AADD;\n"
"                                }")
        self.btn_svm.setObjectName("btn_svm")
        self.verticalLayout_9.addWidget(self.btn_svm)
        self.btn_rffs = QtWidgets.QPushButton(self.frame_classification_buttons)
        self.btn_rffs.setStyleSheet("QPushButton {\n"
"                                    color: #FFF;\n"
"                                    background-color: #232323;\n"
"                                    border: 1px solid #555;\n"
"                                }\n"
"                                QPushButton:hover {\n"
"                                    background-color: #55AADD;\n"
"                                }")
        self.btn_rffs.setObjectName("btn_rffs")
        self.verticalLayout_9.addWidget(self.btn_rffs)
        self.verticalLayout_8.addWidget(self.frame_classification_buttons)
        self.classification_results = QtWidgets.QListWidget(self.page_3)
        self.classification_results.setStyleSheet("background-color: #373737;\n"
"                    color: #FFF;\n"
"                    border: 1px solid #55AADD;")
        self.classification_results.setObjectName("classification_results")
        self.verticalLayout_8.addWidget(self.classification_results)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_91 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_91.setObjectName("verticalLayout_91")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #FFF;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_91.addWidget(self.label_4)
        self.frame_data_visualization_buttons = QtWidgets.QFrame(self.page_4)
        self.frame_data_visualization_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_data_visualization_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_data_visualization_buttons.setObjectName("frame_data_visualization_buttons")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_data_visualization_buttons)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_refresh = QtWidgets.QPushButton(self.frame_data_visualization_buttons)
        self.btn_refresh.setStyleSheet("QPushButton {\n"
"                color: #FFF;\n"
"                background-color: #232323;\n"
"                border: 1px solid #555;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #55AADD;\n"
"            }")
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout_9.addWidget(self.btn_refresh)
        self.btn_draw_chart = QtWidgets.QPushButton(self.frame_data_visualization_buttons)
        self.btn_draw_chart.setStyleSheet("QPushButton {\n"
"                color: #FFF;\n"
"                background-color: #232323;\n"
"                border: 1px solid #555;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #55AADD;\n"
"            }")
        self.btn_draw_chart.setObjectName("btn_draw_chart")
        self.horizontalLayout_9.addWidget(self.btn_draw_chart)
        self.verticalLayout_91.addWidget(self.frame_data_visualization_buttons)
        self.data_list = QtWidgets.QListWidget(self.page_4)
        self.data_list.setStyleSheet("background-color: #373737;\n"
"        color: #FFF;\n"
"        border: 1px solid #55AADD;")
        self.data_list.setObjectName("data_list")
        self.verticalLayout_91.addWidget(self.data_list)
        self.chart_area = QtWidgets.QWidget(self.page_4)
        self.chart_area.setMinimumSize(QtCore.QSize(1200, 600))
        self.chart_area.setStyleSheet("background-color: #232323;\n"
"        border: 1px solid #55AADD;")
        self.chart_area.setObjectName("chart_area")
        self.verticalLayout_91.addWidget(self.chart_area)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.lbl_external_files.setStyleSheet("color: white;")
        self.lbl_local_files.setStyleSheet("color: white;")
        self.list_external_files.setStyleSheet("color: white;")
        self.list_local_files.setStyleSheet("color: white;")
        self.label_2.setStyleSheet("color: white;")
        self.label_3.setStyleSheet("color: white;")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Toggle.setText(_translate("MainWindow", "TOGGLE"))
        self.btn_page_1.setText(_translate("MainWindow", "Band Interface"))
        self.btn_page_2.setText(_translate("MainWindow", "Data Management"))
        self.btn_page_3.setText(_translate("MainWindow", "Data Classification"))
        self.btn_page_4.setText(_translate("MainWindow", "Data Visualization"))
        self.firmware_btn.setText(_translate("MainWindow", "Get Firmware Version"))
        self.led_btn.setText(_translate("MainWindow", "Toggle LED"))
        self.raw_emg_button.setText(_translate("MainWindow", "Get RAW EMG Data"))
        self.gesture_btn.setText(_translate("MainWindow", "Get Gesture ID"))
        self.quaternion_btn.setText(_translate("MainWindow", "Get Quaternion"))
        self.emg_btn.setText(_translate("MainWindow", "Config"))
        self.motor_btn.setText(_translate("MainWindow", "Toggle Motor"))
        self.stop_emg_button.setText(_translate("MainWindow", "Stop EMG Data"))
        self.stop_gesture_btn.setText(_translate("MainWindow", "Stop Gesture ID"))
        self.stop_quat_btn.setText(_translate("MainWindow", "Stop Quaternion"))
        self.scan_btn.setText(_translate("MainWindow", "Scan Devices"))
        self.connect_btn.setText(_translate("MainWindow", "Connect"))
        self.label_2.setText(_translate("MainWindow", "Data Management"))
        self.lbl_local_files.setText(_translate("MainWindow", "Local Files:"))
        self.lbl_external_files.setText(_translate("MainWindow", "External Server Files:"))
        self.btn_upload.setText(_translate("MainWindow", "Upload Data"))
        self.btn_download.setText(_translate("MainWindow", "Download Data"))
        self.lineEdit_filters.setPlaceholderText(_translate("MainWindow", "Apply Filters..."))
        self.label_3.setText(_translate("MainWindow", "Select Classification Method"))
        self.btn_rf.setText(_translate("MainWindow", "Random Forest Classification"))
        self.btn_lr.setText(_translate("MainWindow", "Logistic Regression Classification"))
        self.btn_svm.setText(_translate("MainWindow", "SVM Classification"))
        self.btn_rffs.setText(_translate("MainWindow", "Amplified Random Forest Classification"))
        self.label_4.setText(_translate("MainWindow", "Data Visualization"))
        self.btn_refresh.setText(_translate("MainWindow", "Refresh List"))
        self.btn_draw_chart.setText(_translate("MainWindow", "Draw Chart"))
